kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: candy-mediator2
  annotations:
    description: mediator deployment template
    tags: experimentation, mediator, receiver
objects:
#
# mediator service
#
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: candy-agent
- kind: BuildConfig
  apiVersion: v1
  metadata:
    labels:
      app: candy-agent
    name: candy-agent
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: 'candy-agent:latest'
    resources: {}
    successfulBuildsHistoryLimit: 5
    failedBuildsHistoryLimit: 5
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
    postCommit: {}
    source:
      contextDir: docker
      type: Git
      git:
        uri: 'https://github.com/weiiv/candi-infra.git'
    triggers:
      - type: ConfigChange
    runPolicy: Serial
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: candy-mediator
    labels:
      app: candy-mediator
      app.kubernetes.io/part-of: MultiTenant
  spec:
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - candy-mediator
          from:
            kind: ImageStreamTag
            name: 'candy-agent:latest'
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: candy-mediator
    template:
      metadata:
        labels:
          app: candy-mediator
      spec:
        containers:
          - name: candy-mediator
            command:
              - bash
              - -c
              - $(echo aca-py start
                --inbound-transport http 0.0.0.0 ${HTTP_INTERFACE_PORT}
                --endpoint ${MEDIATOR_ENDPOINT}
                --outbound-transport http
                --admin 0.0.0.0 ${ADMIN_INTERFACE_PORT}
                --label ${LABEL}
                --open-mediation
                --no-ledger
                --admin-insecure-mode
                --debug-connections
                --connections-invite
                --invite-multi-use
                --auto-accept-invites
                --auto-accept-requests
                --auto-ping-connection
                --enable-undelivered-queue);
            env:
              - name: HTTP_INTERFACE_PORT
                value: ${HTTP_INTERFACE_PORT}
              - name: ADMIN_INTERFACE_PORT
                value: ${ADMIN_INTERFACE_PORT}
              - name: LABEL
                value: ${LABEL}
              - name: MEDIATOR_ENDPOINT
                value: ${MEDIATOR_ENDPOINT}
            ports:
              - containerPort: 3000
                protocol: TCP
              - containerPort: 3001
                protocol: TCP
            readinessProbe:
              timeoutSeconds: 30
              initialDelaySeconds: 3
              exec:
                command:
                  - bash
                  - "-c"
                  - 'curl --fail "http://localhost:${ADMIN_INTERFACE_PORT}/status/ready"'
            livenessProbe:
              timeoutSeconds: 30
              initialDelaySeconds: 300
              exec:
                command:
                  - bash
                  - "-c"
                  - 'curl --fail "http://localhost:${ADMIN_INTERFACE_PORT}/status/live"'
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Always
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
- kind: Service
  apiVersion: v1
  metadata:
    name: candy-mediator
  spec:
    selector:
      app: candy-mediator
    ports:
      - name: '3000'
        protocol: TCP
        port: 3000
        targetPort: 3000
      - name: '3001'
        protocol: TCP
        port: 3001
        targetPort: 3001
- kind: Route
  apiVersion: v1
  metadata:
    name: candy-mediator
  spec:
    host: candi-tails-server.apps.ocp1.az.uat.aro.gocloud.gov.on.ca
    to:
      kind: Service
      name: candy-mediator
      weight: 100
    tls:
      termination: edge
    port:
      targetPort: 3000
    wildcardPolicy: None
- kind: Route
  apiVersion: v1
  metadata:
    name: candy-mediator-admin
  spec:
    host: candi-tails-server.apps.ocp1.az.uat.aro.gocloud.gov.on.ca
    to:
      kind: Service
      name: candy-mediator
      weight: 100
    tls:
      termination: edge
    port:
      targetPort: 3001
    wildcardPolicy: None
#
# parameters
#
parameters:
- name: LOG_LEVEL
  displayName: Log Level
  description: The logging level of the agent.
  required: true
  value: "DEBUG"
- name: ADMIN_INTERFACE_PORT
  displayName: Agent Admin Port
  description: The admin port on which the service will listen.
  required: true
  value: "3001"
- name: HTTP_INTERFACE_PORT
  displayName: Agent http port
  description: The http port on which the service will listen.
  required: true
  value: "3000"
- name: LABEL
  displayName: Agent name
  description: The name of the agent.
  required: true
  value: "ODS_SSI_AGENT"
- name: MEDIATOR_ENDPOINT
  displayName: Agent endpoint
  description: The endpoint of the agent.
  required: true
  value: "https://ws.dev.tails-server.candi.gov.on.ca"
